const test=require('node:test');const assert=require('node:assert/strict');
const mem=new Map();global.localStorage={getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};
const C=require('../../assets/js/campaign/campaign-constants');const K=require('../../assets/js/campaign/campaign-catalog');const S=require('../../assets/js/campaign/campaign-store');const {CampaignManager}=require('../../assets/js/campaign/campaign-manager');const R=require('../../assets/js/battle/battle-modifier-resolver');
function fresh(){mem.clear();return new CampaignManager(S)} function start(m){assert.equal(m.start(K.DRAFT.slice(0,6).map(p=>p.id)).ok,true)}
test('CP01–CP10 storage corruption, version, invalid IDs and reset isolation',()=>{mem.set(C.STORAGE_KEY,'{');assert.equal(S.load().status,'NOT_STARTED');mem.set(C.STORAGE_KEY,JSON.stringify({version:99}));assert.equal(S.load().status,'NOT_STARTED');let m=fresh();assert.equal(m.start([1,2,3,4,5,6]).ok,false);start(m);mem.set('team.current','kept');mem.set('trainer.profile','kept');m.reset();assert.equal(mem.get('team.current'),'kept');assert.equal(mem.get('trainer.profile'),'kept');assert.equal(S.load().status,'NOT_STARTED')});
test('CP11–CP37 catalog invariants and disjointness',()=>{assert.equal(K.DRAFT.length,144);assert.equal(new Set(K.DRAFT.map(p=>p.id)).size,144);assert.equal(new Set(K.DRAFT.map(p=>p.generation)).size,9);for(let g=1;g<=9;g++)assert.equal(K.DRAFT.filter(p=>p.generation===g).length,16);assert.equal(new Set(K.DRAFT.flatMap(p=>p.types)).size,18);assert.equal(K.MASTERS.length,18);assert.equal(new Set(K.MASTERS.map(m=>m.type)).size,18);assert.equal(new Set(K.MASTER_SPECIES.map(p=>p.id)).size,54);K.MASTERS.forEach(m=>{assert.equal(m.team.length,3);m.team.forEach(p=>assert.ok(p.types.includes(m.type)))});const d=new Set(K.DRAFT.map(p=>p.id)),masters=new Set(K.MASTER_SPECIES.map(p=>p.id));K.SUPER_TEAM.forEach(p=>{assert.ok(!d.has(p.id));assert.ok(!masters.has(p.id))});assert.ok(K.DRAFT.some(p=>masters.has(p.id)));[132,201,202,235].forEach(id=>assert.ok(!masters.has(id)&&!d.has(id)))});
test('CP38–CP62 draft, progression, pending reward, idempotency and Super unlock',()=>{let m=fresh();assert.equal(m.start(K.DRAFT.slice(0,5).map(p=>p.id)).ok,false);start(m);const steel=K.MASTERS.find(x=>x.challengeId==='master-steel').team.map(x=>x.id);assert.equal(m.reset().status,'NOT_STARTED');assert.equal(m.start([...steel,...K.DRAFT.slice(0,3).map(p=>p.id)]).reason,'MASTER_REWARD_CONFLICT');start(m);assert.equal(m.start(K.DRAFT.slice(1,7).map(p=>p.id)).reason,'IMMUTABLE');for(const master of K.MASTERS){m.recordBattle({battleId:'b'+master.challengeId,kind:'MASTER',id:master.challengeId,winner:'player'});assert.ok(m.getState().pendingReward);assert.equal(m.claimReward(master.team[0].id).ok,true)}assert.equal(m.getBadgeCount(),18);assert.equal(m.getRosterIds().length,24);assert.equal(m.canChallenge('SUPER'),true);assert.equal(m.recordBattle({battleId:'bmaster-normal',kind:'MASTER',id:'master-normal',winner:'player'}).duplicate,true);m.recordBattle({battleId:'super',kind:'SUPER',winner:'player'});assert.deepEqual(m.getState().pendingReward.candidates,K.SUPER_TEAM.map(p=>p.id));assert.equal(m.claimReward(K.SUPER_TEAM[0].id).ok,true);assert.equal(m.getRosterIds().length,25)});
test('CP63–CP80 Shadow visibility, aura matrix and completion',()=>{let m=fresh();start(m);assert.equal(m.canChallenge('SHADOW'),false);for(const n of [0,.25,.5,1,2,4])assert.equal(R.resolveTypeMultiplier(n,{attackerSide:'enemy',modifiers:{SHADOW_AURA:true}}),Math.max(2,n));assert.equal(R.resolveTypeMultiplier(0,{attackerSide:'player',modifiers:{SHADOW_AURA:true}}),0);assert.equal(R.resolveTypeMultiplier(.5,{attackerSide:'enemy',modifiers:{}}),.5);assert.deepEqual(K.SUPER_TEAM.map(p=>p.id),[493,890,150])});
test('Super global audit is deterministic and disjoint',()=>{assert.equal(K.SUPER_AUDIT.length,10);assert.deepEqual(K.SUPER_AUDIT.filter(x=>x.selected).map(x=>x.id),K.SUPER_TEAM.map(x=>x.id));assert.deepEqual(K.SUPER_TEAM.map(x=>x.id),[493,890,150])});



test('full campaign progression persists false ending, reveal and completion',()=>{let m=fresh();start(m);for(const master of K.MASTERS){assert.equal(m.recordBattle({battleId:'e'+master.challengeId,kind:'MASTER',id:master.challengeId,winner:'player'}).processed,true);const candidate=m.getRewardCandidates().find(x=>x.selectable);assert.ok(candidate);assert.equal(m.claimReward(candidate.id).ok,true)}assert.equal(m.getBadgeCount(),18);assert.equal(m.getRosterIds().length,24);assert.equal(m.canChallenge('SUPER'),true);m.recordBattle({battleId:'esuper',kind:'SUPER',winner:'player'});assert.equal(m.getState().superTrainer.victorySeen,false);assert.equal(m.acknowledgeSuperVictory(),true);assert.equal(m.getState().superTrainer.victorySeen,true);const elite=m.getRewardCandidates().find(x=>x.selectable);assert.equal(m.claimReward(elite.id).ok,true);assert.equal(m.getRosterIds().length,25);assert.equal(m.getState().shadowTrainer.revealed,true);assert.equal(m.getState().shadowTrainer.revealSeen,false);assert.equal(m.acknowledgeShadowReveal(),true);assert.equal(m.getState().shadowTrainer.revealSeen,true);m.recordBattle({battleId:'eshadow',kind:'SHADOW',winner:'player'});assert.equal(m.getState().status,'COMPLETED')});

const TypeGuide=require('../../assets/js/campaign/campaign-type-guide');
test('CP81–CP105 canonical campaign metadata has no placeholders and preserves required spot checks',()=>{
  const oldDraft=[3,6,9,143,154,157,160,181,254,257,260,282,389,392,395,461,497,500,503,596,652,655,658,706,724,745,784,733,812,815,818,823,908,911,914,959];
  assert.equal(K.DRAFT.length,144);assert.ok(oldDraft.every(id=>K.DRAFT.some(p=>p.id===id)));
  for(const p of K.DRAFT){assert.doesNotMatch(p.name,/^pokemon-\d+$/i);assert.ok(p.types.length);assert.ok(p.bst>0);assert.ok(p.generation>=1&&p.generation<=9);assert.ok(p.sprite);assert.equal(p.legendary,false);assert.equal(p.mythical,false)}
  const expected={6:['charizard',['fire','flying'],534,1],65:['alakazam',['psychic'],500,1],131:['lapras',['water','ice'],535,1],242:['blissey',['normal'],540,2],248:['tyranitar',['rock','dark'],600,2],350:['milotic',['water'],540,3],384:['rayquaza',['dragon','flying'],680,3]};
  for(const [id,[name,types,bst,generation]] of Object.entries(expected)){const p=K.byId(id);assert.equal(p.name,name);assert.deepEqual(p.types,types);assert.equal(p.bst,bst);assert.equal(p.generation,generation)}assert.equal(K.DRAFT.some(p=>p.id===384),false);
});
test('CP106–CP118 type guide derives strengths and weaknesses from TypeChart',()=>{
  const examples={water:[['fire','ground','rock'],['electric','grass']],fire:[['grass','ice','bug','steel'],['water','ground','rock']],electric:[['water','flying'],['ground']],normal:[[],['fighting']]};
  for(const [type,[strong,weak]] of Object.entries(examples)){const guide=TypeGuide.getTypeGuide(type);assert.deepEqual(guide.offensiveStrengths,strong);assert.deepEqual(guide.defensiveWeaknesses,weak);assert.equal(guide.label,TypeGuide.TYPE_LABELS[type])}
});
test('CP119–CP128 legacy active campaign keeps a formerly eligible canonical roster',()=>{
  const raw={version:C.VERSION,status:'ACTIVE',startedAt:'2026-01-01T00:00:00.000Z',startingRosterIds:[384,3,6,9,143,154],challenges:{},superTrainer:{},shadowTrainer:{},processedBattleIds:[]};
  const restored=S.sanitize(raw);assert.deepEqual(restored.startingRosterIds,raw.startingRosterIds);mem.set(C.STORAGE_KEY,JSON.stringify(raw));const manager=new CampaignManager(S);const rayquaza=manager.getRoster().find(p=>p.id===384);assert.deepEqual(rayquaza.types,['dragon','flying']);assert.equal(rayquaza.bst,680);assert.equal(manager.isStarted(),true);
});
test('CP129–CP136 reward sources and view structure retain readable names and separated CTA',()=>{
  assert.deepEqual(K.MASTERS.find(m=>m.type==='water').team.map(p=>p.name),['lapras','milotic','gastrodon']);assert.deepEqual(K.MASTERS.find(m=>m.type==='normal').team.map(p=>p.name),['blissey','linoone','zangoose']);assert.deepEqual(K.MASTERS.find(m=>m.type==='fire').team.map(p=>p.name),['ninetales','arcanine','chandelure']);
  const fs=require('node:fs'),path=require('node:path'),source=fs.readFileSync(path.join(__dirname,'../../assets/js/campaign/campaign-view.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'../../assets/css/campaign.css'),'utf8');assert.match(source,/GUIA DO TIPO/);assert.match(source,/Tipos secundários podem alterar essas relações\./);assert.match(css,/\.campaign-mon strong,\.campaign-mon small/);
});