const test=require('node:test');const assert=require('node:assert/strict');
const mem=new Map();global.localStorage={getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};
const C=require('../../assets/js/campaign/campaign-constants');const K=require('../../assets/js/campaign/campaign-catalog');const S=require('../../assets/js/campaign/campaign-store');const {CampaignManager}=require('../../assets/js/campaign/campaign-manager');const R=require('../../assets/js/battle/battle-modifier-resolver');
function fresh(){mem.clear();return new CampaignManager(S)} function start(m){assert.equal(m.start(K.DRAFT.slice(0,6).map(p=>p.id)).ok,true)}
test('CP01–CP10 storage corruption, version, invalid IDs and reset isolation',()=>{mem.set(C.STORAGE_KEY,'{');assert.equal(S.load().status,'NOT_STARTED');mem.set(C.STORAGE_KEY,JSON.stringify({version:99}));assert.equal(S.load().status,'NOT_STARTED');let m=fresh();assert.equal(m.start([1,2,3,4,5,6]).ok,false);start(m);mem.set('team.current','kept');mem.set('trainer.profile','kept');m.reset();assert.equal(mem.get('team.current'),'kept');assert.equal(mem.get('trainer.profile'),'kept');assert.equal(S.load().status,'NOT_STARTED')});
test('CP11–CP37 catalog invariants and disjointness',()=>{assert.equal(K.DRAFT.length,36);assert.equal(new Set(K.DRAFT.map(p=>p.id)).size,36);assert.equal(new Set(K.DRAFT.map(p=>p.generation)).size,9);assert.equal(new Set(K.DRAFT.flatMap(p=>p.types)).size,18);assert.equal(K.MASTERS.length,18);assert.equal(new Set(K.MASTERS.map(m=>m.type)).size,18);assert.equal(new Set(K.MASTER_SPECIES.map(p=>p.id)).size,54);K.MASTERS.forEach(m=>{assert.equal(m.team.length,3);m.team.forEach(p=>assert.ok(p.types.includes(m.type)))});const d=new Set(K.DRAFT.map(p=>p.id)),masters=new Set(K.MASTER_SPECIES.map(p=>p.id));K.SUPER_TEAM.forEach(p=>{assert.ok(!d.has(p.id));assert.ok(!masters.has(p.id))});[132,201,202,235].forEach(id=>assert.ok(!masters.has(id)&&!d.has(id)))});
test('CP38–CP62 draft, progression, pending reward, idempotency and Super unlock',()=>{let m=fresh();assert.equal(m.start(K.DRAFT.slice(0,5).map(p=>p.id)).ok,false);start(m);assert.equal(m.start(K.DRAFT.slice(1,7).map(p=>p.id)).reason,'IMMUTABLE');for(const master of K.MASTERS){m.recordBattle({battleId:'b'+master.challengeId,kind:'MASTER',id:master.challengeId,winner:'player'});assert.ok(m.getState().pendingReward);assert.equal(m.claimReward(master.team[0].id).ok,true)}assert.equal(m.getBadgeCount(),18);assert.equal(m.getRosterIds().length,24);assert.equal(m.canChallenge('SUPER'),true);assert.equal(m.recordBattle({battleId:'bmaster-normal',kind:'MASTER',id:'master-normal',winner:'player'}).duplicate,true);m.recordBattle({battleId:'super',kind:'SUPER',winner:'player'});assert.deepEqual(m.getState().pendingReward.candidates,K.SUPER_TEAM.map(p=>p.id));assert.equal(m.claimReward(K.SUPER_TEAM[0].id).ok,true);assert.equal(m.getRosterIds().length,25)});
test('CP63–CP80 Shadow visibility, aura matrix and completion',()=>{let m=fresh();start(m);assert.equal(m.canChallenge('SHADOW'),false);for(const n of [0,.25,.5,1,2,4])assert.equal(R.resolveTypeMultiplier(n,{attackerSide:'enemy',modifiers:{SHADOW_AURA:true}}),Math.max(2,n));assert.equal(R.resolveTypeMultiplier(0,{attackerSide:'player',modifiers:{SHADOW_AURA:true}}),0);assert.equal(R.resolveTypeMultiplier(.5,{attackerSide:'enemy',modifiers:{}}),.5);assert.deepEqual(K.SUPER_TEAM.map(p=>p.id),[493,890,150])});
test('Super global audit is deterministic and disjoint',()=>{assert.equal(K.SUPER_AUDIT.length,10);assert.deepEqual(K.SUPER_AUDIT.filter(x=>x.selected).map(x=>x.id),K.SUPER_TEAM.map(x=>x.id));assert.deepEqual(K.SUPER_TEAM.map(x=>x.id),[493,890,150])});

